//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhi
    {
        public int ID_CP { get; set; }
        public int ID_DMCP { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaCB { get; set; }
        public double SoTien { get; set; }
        public bool Status { get; set; }
        public int MaCBth { get; set; }
        public Nullable<int> Trangthai_CP { get; set; }
        public Nullable<byte> PhanLoai { get; set; }
    
        public virtual DM_CP DM_CP { get; set; }
    }
}
