//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public int IDCV { get; set; }
        public string TenChucVu { get; set; }
        public Nullable<int> Status { get; set; }
        public int SoTT { get; set; }
    }
}
