//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhCT
    {
        public int IDCT { get; set; }
        public Nullable<int> IDCTDG { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string DanhGia { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChuongTrinhDanhGia ChuongTrinhDanhGia { get; set; }
    }
}
