//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhDanhGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuongTrinhDanhGia()
        {
            this.ChuongTrinhCTs = new HashSet<ChuongTrinhCT>();
            this.PhatHienDanhGias = new HashSet<PhatHienDanhGia>();
            this.ThanhPhanDanhGias = new HashSet<ThanhPhanDanhGia>();
        }
    
        public int IDCTDG { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaLHDG { get; set; }
        public Nullable<int> SoNgayDanhGia { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string NhanXet { get; set; }
        public string IDTL { get; set; }
        public int NoiDanhGia { get; set; }
        public int DVDanhGia { get; set; }
        public int MaCBth { get; set; }
        public Nullable<System.DateTime> NgayTraKQTN { get; set; }
        public string DonViThuNghiem { get; set; }
        public Nullable<System.DateTime> NgayBanGiaoMau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuongTrinhCT> ChuongTrinhCTs { get; set; }
        public virtual LoaiHinhDanhGia LoaiHinhDanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhatHienDanhGia> PhatHienDanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhPhanDanhGia> ThanhPhanDanhGias { get; set; }
    }
}
