//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongVan
    {
        public int IDCV { get; set; }
        public Nullable<int> MaHD { get; set; }
        public string NoiDung { get; set; }
        public string File { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> PhanLoai { get; set; }
        public Nullable<System.DateTime> NgayGuiNhan { get; set; }
        public int MaCB { get; set; }
        public int MaCBth { get; set; }
        public string GhiChu { get; set; }
    }
}
