//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMCanBo
    {
        public int MaCB { get; set; }
        public string TenCB { get; set; }
        public string PhongBan { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public string QueQuan { get; set; }
        public Nullable<int> IDCV { get; set; }
        public int PhanLoai { get; set; }
        public string NaceCode { get; set; }
        public string SoCMTND { get; set; }
        public Nullable<System.DateTime> NgayCapCMTND { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> MoiGioi { get; set; }
    }
}
