//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMNaceCode
    {
        public string NaceCode { get; set; }
        public string NganhKinhTe { get; set; }
        public string NganhKinhTeUS { get; set; }
        public string GhiChu { get; set; }
    }
}
