//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaTriHD
    {
        public int IdGiaTriHD { get; set; }
        public int MaHD { get; set; }
        public int PhanLoai { get; set; }
        public string NoiDung { get; set; }
        public double SoTien { get; set; }
        public System.DateTime NamTToan { get; set; }
        public int TrangThaiTT { get; set; }
        public string GhiChu { get; set; }
    }
}
