//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDLD
    {
        public string MaHDLD { get; set; }
        public int MaCB { get; set; }
        public int Status { get; set; }
        public int LoaiHD { get; set; }
        public int ThoiHan { get; set; }
        public Nullable<double> MucLuong { get; set; }
    }
}
