//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeThong
    {
        public int IDHT { get; set; }
        public string TenDV { get; set; }
        public string MaSoThue { get; set; }
        public string DienThoai { get; set; }
        public string Website { get; set; }
        public string ThuTruongDV { get; set; }
        public string Email { get; set; }
        public string logo { get; set; }
        public string Fax { get; set; }
        public string TruSo { get; set; }
        public string Vicas { get; set; }
        public string SoTaiKhoan { get; set; }
        public string FomatDate { get; set; }
    }
}
