//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public string MaKH { get; set; }
        public string TenHD { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<System.DateTime> NgayDeNghi { get; set; }
        public Nullable<System.DateTime> NgayChungNhan { get; set; }
        public int MaTC { get; set; }
        public string PhamViDanhGia { get; set; }
        public string HeThongQL { get; set; }
        public string QLHoSo { get; set; }
        public Nullable<int> Status { get; set; }
        public string PhamViSanPham { get; set; }
        public string LoaiTru { get; set; }
        public string PhuongThuc { get; set; }
        public Nullable<int> SoNhanVien { get; set; }
        public string SoLuong { get; set; }
        public Nullable<double> GiaTriHD { get; set; }
        public int IDLoaiHD { get; set; }
        public int HDKy { get; set; }
        public int PhanLoai { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public Nullable<int> TrangThaiTT { get; set; }
        public string PhamViDanhGiaUS { get; set; }
        public string SoChungChi { get; set; }
        public string NaceCode { get; set; }
        public int LanChungNhan { get; set; }
        public string MaQD { get; set; }
        public int MaHD { get; set; }
        public string VicasHD { get; set; }
        public int MaCBth { get; set; }
        public string MaDG { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayChungNhanSP { get; set; }
        public Nullable<System.DateTime> NgayHetHanSP { get; set; }
        public string SoChungNhanSP { get; set; }
        public string VicasSP { get; set; }
        public string TieuChuanSP { get; set; }
        public Nullable<int> MaCBPhuTrach { get; set; }
    }
}
