//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISOEntities : DbContext
    {
        public ISOEntities()
            : base("name=ISOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Checklist> Checklists { get; set; }
        public virtual DbSet<ChiPhi> ChiPhis { get; set; }
        public virtual DbSet<ChiPhict> ChiPhicts { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<ChuongTrinhCT> ChuongTrinhCTs { get; set; }
        public virtual DbSet<ChuongTrinhDanhGia> ChuongTrinhDanhGias { get; set; }
        public virtual DbSet<CongVan> CongVans { get; set; }
        public virtual DbSet<DM_CP> DM_CP { get; set; }
        public virtual DbSet<DMCanBo> DMCanBoes { get; set; }
        public virtual DbSet<DMNaceCode> DMNaceCodes { get; set; }
        public virtual DbSet<DMTaiLieu> DMTaiLieux { get; set; }
        public virtual DbSet<DoiTuongPQ> DoiTuongPQs { get; set; }
        public virtual DbSet<GiaTriHD> GiaTriHDs { get; set; }
        public virtual DbSet<HDLD> HDLDs { get; set; }
        public virtual DbSet<HeThong> HeThongs { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiHD> LoaiHDs { get; set; }
        public virtual DbSet<LoaiHinhDanhGia> LoaiHinhDanhGias { get; set; }
        public virtual DbSet<PhamViDG> PhamViDGs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PhatHienDanhGia> PhatHienDanhGias { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<ThamXet> ThamXets { get; set; }
        public virtual DbSet<ThanhPhanDanhGia> ThanhPhanDanhGias { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<ThongBaoCT> ThongBaoCTs { get; set; }
        public virtual DbSet<TieuChuan> TieuChuans { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
    }
}
