//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> MaCBQL { get; set; }
        public string NguoiDaiDien { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string TruSo { get; set; }
        public string TruSoKhac { get; set; }
        public string SoDienThoai { get; set; }
        public string MaSoThue { get; set; }
        public string Fax { get; set; }
        public string ChucVu_NguoiDaiDien { get; set; }
        public string TruSoUS { get; set; }
        public string TruSoKhacUS { get; set; }
        public string SoTaiKhoan { get; set; }
        public string LienHe { get; set; }
        public int MaCBth { get; set; }
    }
}
