//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhamViDG
    {
        public int IDCTDG { get; set; }
        public string HangHoa { get; set; }
        public string HangHoaUS { get; set; }
        public string TSKyThuat { get; set; }
        public string LuongMau { get; set; }
        public string GhiChu { get; set; }
        public int IDPhamViDG { get; set; }
        public string QuyChuan { get; set; }
        public Nullable<int> CBLayMau { get; set; }
    }
}
