//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhatHienDanhGia
    {
        public int IDPHDG { get; set; }
        public int IDCTDG { get; set; }
        public string MaCanCu { get; set; }
        public string DanhGia { get; set; }
        public string KetLuan { get; set; }
        public string PhatHien { get; set; }
        public int MaCB { get; set; }
    
        public virtual ChuongTrinhDanhGia ChuongTrinhDanhGia { get; set; }
    }
}
