//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahAppsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamXet
    {
        public int MaHD { get; set; }
        public int ID { get; set; }
        public int MaCB_TX { get; set; }
        public System.DateTime NgayThamXet { get; set; }
        public string GhiChu { get; set; }
        public int PLoai { get; set; }
        public Nullable<int> KetLuan { get; set; }
        public int MaCBth { get; set; }
    }
}
